name: Web E2E Tests

on:
    workflow_dispatch:

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            # clone do projeto para máquina
            - uses: actions/checkout@v4

            #Conferir a versão instalada
            - name: Node version
              run: node --version

            - name: Instalando dependências
              run: npm install

            - name: Executando os teste
              run: npx cypress run --reporter mochawesome

            - uses: actions/upload-artifact@v4
              if: ${{!cancelled()}}
              with:
                name: relatorios
                path: |
                    - cypress/reports
                    - cypress/videos
                    - cypress/screenshots